name: flutter_document_scanner
description: A Flutter plugin that allows the management of taking, cropping and applying filters to an image, using the camera plugin
version: 0.1.0
homepage: https://github.com/criistian14/flutter_document_scanner

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.9.4+8
  path_provider: ^2.0.8
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  bloc_test: ^9.0.2

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.christian.flutter_document_scanner
        pluginClass: FlutterDocumentScannerPlugin
      ios:
        pluginClass: FlutterDocumentScannerPlugin