name: flutter_document_scanner_platform_interface
description: A common platform interface for the flutter_document_scanner plugin.
repository: https://github.com/criistian14/flutter_document_scanner/tree/master/flutter_document_scanner_platform_interface
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
